### ISSUE TITLE
Override Templates

### ISSUE THREAD

**Issue by Felipemauah** [madrasthemes/mas-wp-job-manager-company#17]
Hello!! Your work is great guys!!!!
My question is about override templates. Iam use the same logic on the Wp Job Manager Override templates?

Thanks for this great work!!

**Comment by ibndawood** [comment]
Hello there,

Apologies for the delay in response. Yes, you can override the templates like you do for WP Job Manager. You'll have to place the templates inside the `templates/wp-job-manager-company` folder.

Hope this answers your question. Let us know if you have any other questions.

Thanks,
Ibrahim
