### ISSUE TITLE
No company selection possible

### ISSUE THREAD

**Issue by jordijaques** [madrasthemes/mas-wp-job-manager-company#21]
It is not possible to select the company in the backend for a specific job. "No companies found" is displayed.
As admin, the function must be that a specific job can be assigned to a specific company.
There are already some companies recorded, which means that also companies should be available for selection.

See: https://i.imgur.com/PJ5qPhs.png

**Comment by ibndawood** [comment]
Companies are populated once there are companies that are published. Please make sure there are published companies.

**Comment by ibndawood** [comment]
I'd recommend that you use wordpress.org for support. We are trying to use GitHub for feature requests and bugs.
