### ISSUE TITLE
General CSS class conflicts

### ISSUE THREAD

**Issue by HlebP** [madrasthemes/mas-wp-job-manager-company#23]
Hello, thank you for the nice plugin.

I have a suggestion - there is a CSS class widely used in many-many themes - '.container'.

And such rules affect page layout not only when it is expected, but all .container elements on the page - header, footer etc.: 
`.single-company .container {
    max-width: 80%;
    margin: 0 10%;
    padding: 0 60px;
}`

The suggestion is to change a selector or a class name so the theme-compatilibily will be improved.

Thank you!

**Comment by ibndawood** [comment]
Hello there,

Thank you for trying our plugin and for your comments. The plugin uses the name `.container` from the Bootstrap classes. You can always dequeue the CSS and override the class using the pluggable function.

Hope this helps. Let us know if you have any other questions or need further help.

Thanks,
Ibrahim
